### ISSUE TITLE
what's wrong with this shape

### ISSUE THREAD

**Issue by carvendy** [kushalvyas/Python-Multiple-Image-Stitching#10]
ERROR message:

Homography is :  [[ 1.11586213e+00  1.19044409e-01 -3.01716625e+01]
 [-1.01242874e-02  1.15190229e+00 -1.65935441e+02]
 [-7.71350676e-06  4.66283837e-04  1.00000000e+00]]
Inverse Homography : [[ 8.95363909e-01 -9.69551305e-02  1.09263253e+01]
 [ 8.30646912e-03  8.12587954e-01  1.35087761e+02]
 [ 3.03322327e-06 -3.79644493e-04  9.37095041e-01]]
final ds=> [501.39889108 488.45946558   1.        ]
image dsize => (432, 687)
Traceback (most recent call last):
  File "pano.py", line 138, in <module>
    s.leftshift()
  File "pano.py", line 54, in leftshift
    tmp[offsety:b.shape[0]+offsety, offsetx:b.shape[1]+offsetx] = b
ValueError: could not broadcast input array from shape (320,480,3) into shape (320,421,3)

**Comment by zheng-xing** [comment]
I see similar shape error too. Did you figure out why?

**Comment by dek8v5** [comment]
I encounter the same problem. Anyone com up with a solution?

**Comment by kcsmta** [comment]
same error for my images.  Anyone solved?
